name: pulip_webapp
description: Pulip WebApp - 하이브리드 모바일 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # WebView
  webview_flutter: ^4.4.2
  webview_flutter_wkwebview: ^3.9.4
  
  # Firebase (임시 제거 - 빌드 문제 해결)
  # firebase_core: ^3.6.0
  # firebase_messaging: ^15.1.3
  
  # HTTP 요청
  http: ^1.1.2
  
  # 로컬 스토리지
  shared_preferences: ^2.2.2
  
  # URL 처리
  url_launcher: ^6.2.2
  
  # 상태 관리
  provider: ^6.1.1
  
  # 로딩 인디케이터 (Flutter 기본 위젯 사용)
  # flutter_spinkit: ^5.1.0
  
  # 권한 관리 (임시 제거 - Android embedding v2 호환성 문제)
  # permission_handler: ^11.2.0
  
  # 디바이스 정보 (임시 제거 - Android embedding v2 호환성 문제)
  # device_info_plus: ^9.1.1
  
  # 패키지 정보 (임시 제거 - Android embedding v2 호환성 문제)
  # package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # 앱 아이콘 및 스플래시 이미지
  assets:
    - assets/
    - assets/icons/