name: Minimal Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  minimal-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: minimal-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
      
      - name: Success
        run: echo "✅ Minimal build completed successfully!"
