name: Test Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze
        run: flutter analyze --no-fatal-infos
      
      - name: Test
        run: flutter test
      
      - name: Build Debug APK
        run: flutter build apk --debug
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: test-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
      
      - name: Build Summary
        run: |
          echo "## 🧪 Test Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Generated**: Debug APK" >> $GITHUB_STEP_SUMMARY
          echo "- **Note**: This is a test build without signing" >> $GITHUB_STEP_SUMMARY
